CREATE DATABASE IF NOT EXISTS RSS;
DROP TABLE IF EXISTS feeds;
CREATE TABLE `RSS`.`feeds` ( `date` VARCHAR(32) NOT NULL , 
`time` VARCHAR(32) NOT NULL ,
`title` VARCHAR(64) NOT NULL ,
`description` VARCHAR(350) NOT NULL ) ENGINE = MyISAM;